Add check for undefined slug and blog
Rahilsiddique/next-blog pull request #11
Opened 2023-10-02 17:57 UTC by rupeshghosh10

Added check to ensure that the file exists and that the slug is defined before proceeding with the following method call:
```ts
const content = fs.readFileSync(file, "utf8");
``` 

resolve #6

2023-10-02 18:26 UTC, Rahilsiddique commented
@rupeshghosh10 good work, perpahs a simple `NotFound.ts` would be even more useful as `noFound()` function is just
throwing the custom vercel/next.js dark page 
refer docs https://nextjs.org/docs/app/api-reference/file-conventions/not-found for even better implimentation

2023-10-02 18:27 UTC, Rahilsiddique requested changes
add a simple NotFound file

2023-10-03 03:22 UTC, rupeshghosh10 commented
Hi @Rahilsiddique, I have added a simple not found page. Please have a look

2023-10-03 12:07 UTC, Rahilsiddique approved these changes
thanks for the contribution @rupeshghosh10

2023-10-03 12:07 UTC, merged